name: CI - Security Enhanced

on:
  push:
    branches: [master, main, 'feature/*', 'security/*']
  pull_request:
    branches: [master, main]
    types: [opened, synchronize, reopened]

# Cancel in-progress runs when a new run is queued
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Pre-flight checks for environment and secrets
  preflight:
    name: Pre-flight Checks
    runs-on: ubuntu-latest
    outputs:
      has-openai-key: ${{ steps.check-secrets.outputs.has-openai-key }}
      has-stripe-secret: ${{ steps.check-secrets.outputs.has-stripe-secret }}
    steps:
      - name: Check required secrets
        id: check-secrets
        run: |
          echo "has-openai-key=${{ secrets.OPENAI_API_KEY != '' }}" >> $GITHUB_OUTPUT
          echo "has-stripe-secret=${{ secrets.STRIPE_WEBHOOK_SECRET != '' }}" >> $GITHUB_OUTPUT
          
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "⚠️  Warning: OPENAI_API_KEY not set - some tests will be skipped"
          fi
          
          if [ -z "${{ secrets.STRIPE_WEBHOOK_SECRET }}" ]; then
            echo "⚠️  Warning: STRIPE_WEBHOOK_SECRET not set - webhook tests will be skipped"
          fi

  # Code quality checks - MUST PASS
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript check
        run: pnpm tsc --noEmit

      - name: Run ESLint
        run: pnpm lint
        continue-on-error: false  # MUST pass

      - name: Check formatting with Prettier
        run: pnpm prettier --check "**/*.{ts,tsx,js,jsx,json,md}"

      - name: Check for console.log in production code
        run: |
          # Exclude test files and check for console.log
          if grep -r "console\.log" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
             --exclude-dir="tests" --exclude-dir="test-results" --exclude-dir="node_modules" \
             --exclude="*test*" --exclude="*spec*" apps/; then
            echo "❌ Found console.log statements in production code!"
            exit 1
          else
            echo "✅ No console.log found in production code"
          fi

  # Security scanning - MUST PASS
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    needs: preflight
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run pnpm audit
        run: pnpm audit --recursive
        continue-on-error: true  # Log but don't fail for now

      - name: Check for exposed secrets
        run: |
          # Check for potential exposed secrets
          if grep -r -E "(api[_-]?key|secret|password|token)" --include="*.ts" --include="*.js" \
             --exclude-dir="node_modules" --exclude-dir="test*" . | \
             grep -v -E "(process\.env|import|require|interface|type|\.test\.|\.spec\.)"; then
            echo "⚠️  Warning: Potential exposed secrets found!"
          else
            echo "✅ No exposed secrets detected"
          fi

      - name: License compatibility check
        run: |
          # Basic license check - ensure no GPL licenses in production deps
          echo "Checking production dependency licenses..."
          pnpm licenses list --prod || true

  # Build and unit tests
  build-and-test:
    name: Build & Test (${{ matrix.os }}, Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    needs: [code-quality, security-scan]
    strategy:
      fail-fast: false  # Continue testing other combinations if one fails
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NODE_ENV: test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Start Dev Server
        run: |
          pnpm run dev &
          # Wait for the dev server to start
          pnpm --filter ./apps/ui exec wait-on http://localhost:5174

      - name: Build all packages
        run: pnpm build
        
      - name: Run unit tests
        run: pnpm test
        if: always()  # Run even if build fails
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-node${{ matrix.node-version }}
          path: |
            test-results/
            coverage/

  # Playwright E2E tests
  e2e-tests:
    name: E2E Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
        
      - name: Build application
        run: pnpm build
        
      - name: Run Playwright tests
        run: pnpm test:e2e
        continue-on-error: true  # Don't fail the whole pipeline
        
      - name: Upload Playwright results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-results
          path: |
            playwright-report/
            test-results/

  # Package validation (test built app)
  package-validation:
    name: Package Validation
    runs-on: ${{ matrix.os }}
    needs: [build-and-test, e2e-tests]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build and package app
        run: |
          pnpm build
          pnpm package
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false  # Skip code signing in CI
          
      - name: Test packaged app
        run: node tests/test-packaged-app.js
        if: runner.os != 'macOS'  # Skip on macOS due to code signing issues
        continue-on-error: true
        
      - name: Upload packaged app
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app-${{ matrix.os }}
          path: dist/*

  # Final status check - ALL MUST PASS
  status-check:
    name: CI Status Check
    runs-on: ubuntu-latest
    needs: [
      preflight,
      code-quality,
      security-scan,
      build-and-test,
      e2e-tests,
      package-validation
    ]
    if: always()
    steps:
      - name: Check all job statuses
        run: |
          echo "Checking CI pipeline status..."
          
          # Check if any required jobs failed
          if [ "${{ needs.code-quality.result }}" != "success" ]; then
            echo "❌ Code quality checks failed!"
            exit 1
          fi
          
          if [ "${{ needs.security-scan.result }}" != "success" ]; then
            echo "❌ Security scanning failed!"
            exit 1
          fi
          
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "❌ Build and test failed!"
            exit 1
          fi
          
          echo "E2E Tests result: ${{ needs.e2e-tests.result }}"
          echo ""
          echo "Optional check results:"
          echo "- Package Validation: ${{ needs.package-validation.result }}"

  Test-Core-Functionality:
    runs-on: ubuntu-latest
    needs: [Install-Dependencies]
    steps:
      # ... existing code ...

      - name: Run E2E tests
        run: pnpm test:e2e
        env:
          VITE_DEV_SERVER_URL: http://localhost:5174 