name: 🛠 Package installers
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - name: Get version from package.json
        id: version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Compute SHA-256
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec shasum -a 256 {} \; > dist/SHA256SUMS.txt || true
          else
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec sha256sum {} \; > dist/SHA256SUMS.txt || true
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: installers-${{ runner.os }}
          path: dist/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@v4
        with:
          name: installers-macOS
          path: artifacts/
      - uses: actions/download-artifact@v4
        with:
          name: installers-Windows
          path: artifacts/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: A-B/AI v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          body_path: release-notes.md
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.zip
            artifacts/**/SHA256SUMS.txt
          token: ${{ secrets.GITHUB_TOKEN }}

 