name: 🛠 Package installers
on:
  push:
    branches: [master]
permissions:
  contents: write
  packages: write
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - name: Compute SHA-256
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec shasum -a 256 {} \; > dist/SHA256SUMS.txt || true
          else
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec sha256sum {} \; > dist/SHA256SUMS.txt || true
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: installers-${{ runner.os }}
          path: dist/**/*

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: installers-macOS
          path: artifacts/
      - uses: actions/download-artifact@v4
        with:
          name: installers-Windows
          path: artifacts/
      - name: Check if release exists
        id: check_release
        run: |
          if gh release view v1.0.0 >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Tag
        if: steps.check_release.outputs.exists == 'false'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v1.0.0 -m "Release v1.0.0" || echo "Tag already exists"
          git push origin v1.0.0 || echo "Tag already pushed"
          
      - name: Create Release
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.zip
            artifacts/**/SHA256SUMS.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update existing release
        if: steps.check_release.outputs.exists == 'true'
        run: |
          echo "Release v1.0.0 already exists. Uploading additional assets..."
          for file in artifacts/**/*.{exe,dmg,zip,txt}; do
            if [ -f "$file" ]; then
              gh release upload v1.0.0 "$file" --clobber || echo "Failed to upload $file"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 