name: 🛠 Package installers
on:
  push:
    branches: [master]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm package
      - name: Compute SHA-256
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec shasum -a 256 {} \; > dist/SHA256SUMS.txt || true
          else
            find dist -type f \( -name "*.exe" -o -name "*.dmg" -o -name "*.zip" \) -exec sha256sum {} \; > dist/SHA256SUMS.txt || true
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: installers-${{ runner.os }}
          path: dist/**/*

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: installers-macOS
          path: artifacts/
      - uses: actions/download-artifact@v4
        with:
          name: installers-Windows
          path: artifacts/
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          name: Release v1.0.0
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
            artifacts/**/*.zip
            artifacts/**/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 