name: 📄 Pages Stub

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Determine deploy necessity
        id: decide
        run: |
          if [[ "${{ github.ref }}" =~ refs/tags/v.* ]]; then
            echo "deploy_docs=true" >> $GITHUB_OUTPUT
          else
            echo "deploy_docs=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo
        uses: actions/checkout@v4
        if: steps.decide.outputs.deploy_docs == 'true'

      - name: Upload docs for tag deploy
        if: steps.decide.outputs.deploy_docs == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Upload placeholder for regular push
        if: steps.decide.outputs.deploy_docs == 'false'
        run: echo '<!doctype html><title>No Pages deploy for this commit</title>' > index.html

      - name: Upload placeholder artifact
        if: steps.decide.outputs.deploy_docs == 'false'
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 