name: 📄 Pages Stub

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Decide
        uses: actions/checkout@v4

      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy
        uses: actions/deploy-pages@v4